name: Merge after test
# auto merge test
on:
  workflow_run:
    workflows: ["PHPStan Analyze && PHPUnit Test"]
    types:
      - completed
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          source_ref: "develop"
          target_branch: "production"
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"
