name: deploy-to-subdomain
run-name: Deploy Changes to Ronins Server
on: 
  # push:
  #   branches:
  #     - production
  release:
    types:
      - created
jobs:

  deploy-to-ronins:
    name: Deploy to Ronins server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH and Deploy changes to Ronins Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          port: ${{ vars.PORT_SERVER }}

          # BRANCH BASED DEPLOYMENT
          # script: | 
          #   cd ${{ secrets.DEPLOYMENT_DIRECTORY }}
          #   eval "$(ssh-agent)"
          #   ssh-add ${{ secrets.SSH_P_KEY_PATH }}
          #   git pull origin ${{ vars.SOURCE_BRANCH_PULL }}
          #   /usr/local/php82/bin/php composer.phar install --no-dev
          #   /usr/local/php82/bin/php artisan migrate --force

          # TAG BASED DEPLOYMENT
          # Fetches and Checkouts the latest tag from remote repo
          script: |
            cd ${{ secrets.DEPLOYMENT_DIRECTORY }}
            bash ${{ secrets.FETCH_CHECKOUT_TAG_SCRIPT_PATH }}
            ${{ vars.PHP_BINARY_PATH }} composer.phar install --no-dev
            ${{ vars.PHP_BINARY_PATH }} artisan migrate --force
            ${{ vars.PHP_BINARY_PATH }} artisan config:cache
            ${{ vars.PHP_BINARY_PATH }} artisan event:cache
            ${{ vars.PHP_BINARY_PATH }} artisan route:cache
            ${{ vars.PHP_BINARY_PATH }} artisan view:cache