name: PHPStan Analyze && PHPUnit Test
run-name: PHPStan Analyze and PHPUnit Test

on:
  push:
    branches:
      - develop

jobs:

  phpstan-analyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    
    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v3
      with:
        path: app/ config/ database/ public/ routes/web.php tests/ resources/
  
  phpunit-test:

    runs-on: ubuntu-latest

    # needs: phpstan-analyze
      
    steps:
    - uses: actions/checkout@v3
    - name: Copy .env.testing
      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Create Sqlite Database
      run: touch database/database.sqlite

    - name: Migrate Tables to Sqlite Database
      env: 
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate

    - name: Run php unit test
      env: 
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test