name: PHPStan Analyze && PHPUnit Test
run-name: doing continuous integration to repo

on:
  push:
    branches:
      - develop

jobs:
  phpstan-analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    
    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v3
      with:
        path: app/ config/ database/ public/ routes/web.php tests/ resources/
  
  phpunit-test:
    env: 
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Migrate Tables to Sqlite Database
      run: php artisan migrate --database=sqlite

    - name: Run php unit test
      run: vendor/bin/phpunit